name: Run Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Tests
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.19
          bundle _2.4.19_ install

      - name: Run tests
        run: bundle _2.4.19_ exec rspec